### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thomasandersen77** [perottobc/co-pilot#7]
Got this error when running `co-pilot status`         
```
WARN[0000] could not find any dependencies              
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x8844c1]

goroutine 1 [running]:
co-pilot/pkg/upgrade.Plugin(0xc00011f380, 0x9853db, 0x2)
	/home/user/git/co-pilot/pkg/upgrade/plugin.go:10 +0x41
co-pilot/cmd.glob..func11(0xd9e840, 0xdd4460, 0x0, 0x0)
	/home/user/git/co-pilot/cmd/status.go:44 +0x420
github.com/spf13/cobra.(*Command).execute(0xd9e840, 0xdd4460, 0x0, 0x0, 0xd9e840, 0xdd4460)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xda0fa0, 0x443bea, 0xd5c740, 0xc000000180)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
co-pilot/cmd.Execute()
	/home/user/git/co-pilot/cmd/root.go:44 +0x31
main.main()
	/home/user/git/co-pilot/main.go:22 +0x20
```

**Comment by perottobc** [comment]
fixed
